import {I} from '../components/Icon';
import {NextClass} from '../components/NextClass';
import {Timeline} from '../components/Timeline';
import {InstallCard} from '../components/InstallCard';
import {schedule} from '../data/schedule';
import {specialDays} from '../data/specialDays';
import {getDay,nowMinutes,mins,humanDuration} from '../utils/time';
import {subjectByCode} from '../data/subjects';
import type {ScheduleEntry} from '../types';
export function Home({now,install,canInstall,onSelect}:{now:Date;install:()=>void;canInstall:boolean;onSelect:(e:ScheduleEntry)=>void}){
 const day=getDay(now); const today=schedule.filter(x=>x.day===day && x.kind!=='activity').sort((a,b)=>mins(a.start)-mins(b.start)); const n=nowMinutes(now); const current=today.find(x=>n>=mins(x.start)&&n<mins(x.end)); const next=today.find(x=>mins(x.start)>n); const completed=today.filter(x=>mins(x.end)<=n).length; const special=specialDays.find(x=>x.date===now.toISOString().slice(0,10)); const upcoming=specialDays.filter(x=>new Date(x.date+'T00:00:00')>new Date(now.toISOString().slice(0,10)+'T00:00:00')).slice(0,3); const greeting=now.getHours()<12?'Good Morning':now.getHours()<17?'Good Afternoon':'Good Evening'; const classes=today.filter(x=>x.kind==='class'||x.kind==='sports'); const total=classes.reduce((a,x)=>a+mins(x.end)-mins(x.start),0);
 return <div className="page"><div className="hero"><div className="hero-logo"><img src="/icons/icon-64.png"/></div><div><div className="eyebrow">{greeting}</div><h1>REC Mainpuri</h1><p>Electrical Engineering</p><span>B.Tech First Year • I Semester</span></div></div><div className="date-row"><div><b>{now.toLocaleDateString('en-IN',{weekday:'long'})}</b><span>{now.toLocaleDateString('en-IN',{day:'numeric',month:'long',year:'numeric'})}</span></div><div className="session">2026–27</div></div>{special&&<section className="special-card"><div className="special-icon">{special.icon}</div><div><span className="eyebrow">TODAY'S SPECIAL DAY</span><h3>{special.title}</h3><p>{special.subtitle}</p></div></section>}<NextClass current={current} next={next} nowMin={n}/><div className="stats"><div><b>{classes.length}</b><span>Today</span></div><div><b>{completed}</b><span>Completed</span></div><div><b>{Math.max(0,classes.length-completed)}</b><span>Remaining</span></div><div><b>{next?new Date(2000,0,1,Math.floor(mins(next.start)/60),mins(next.start)%60).toLocaleTimeString('en-IN',{hour:'numeric',minute:'2-digit'}):'—'}</b><span>Next</span></div></div><section><div className="section-head"><div><span className="eyebrow">TODAY'S SCHEDULE</span><h2>{day}</h2></div><span className="muted">{humanDuration(total)} scheduled</span></div>{day==='Sunday'?<div className="empty-card">No regular timetable on Sunday.</div>:<Timeline items={today} nowMin={n} onSelect={onSelect}/>}</section>{upcoming.length>0&&<section><div className="section-head"><div><span className="eyebrow">UPCOMING</span><h2>Special days</h2></div></div><div className="upcoming-list">{upcoming.map(x=><div className="upcoming" key={x.date}><span>{x.icon}</span><div><b>{x.title}</b><small>{new Date(x.date+'T00:00:00').toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'})}</small></div></div>)}</div></section>}<InstallCard onInstall={install} canInstall={canInstall}/><div className="source-note"><I.Info size={15}/> Official timetable: effective 25/08/2026 • Tentative • Room EES03</div></div>
}
